#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(3)

@sdfg
def _():

  #@...
  @untwisted.identity(listen().then)
  class server(smtp.server):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.server.mail):
        def sender(ctx, sender):
          ctx.sender = sender

          for cursor in conn:
            equiv(((str(sender.localPart),),), cursor.execute('SELECT sender FROM address WHERE address = %s', 'bob@example.com'))

        recipient = staticmethod(untwisted.each(lambda: equal('bob@example.com', str((yield)))))
        content = lambda ctx, content: equal('\r\n'.join((
          'Received: from example.com (localhost [127.0.0.1])',
          '  by example.com (Postfix) with ESMTPA',
          '  for <notBob@example.com>; Fri, 13 Feb 2009 15:31:30 -0800 (PST)',
          'From: ' + str(ctx.sender),
          '',
          'Expect')), content)

      ctx = yield sample.__get__(ctx)()

      # QUIT
      yield smtp.server.mail.__get__(ctx)()

  #@...
  @untwisted.identity(connect().then)
  class client(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.client.mail):
        sender = iter(('alice@example.com',)).next
        recipient = iter(('bob@example.com',)).next
        content = iter(('\r\n'.join((
          'Received: from example.com (localhost [127.0.0.1])',
          '  by example.com (Postfix) with ESMTPA',
          '  for <notBob@example.com>; Fri, 13 Feb 2009 15:31:30 -0800 (PST)',
          'From: notAlice@example.com',
          '',
          'Expect')),)).next

      yield sample.__get__(ctx)()

  return client
