#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(4)

@sdfg
def _():
  for cursor in conn:
    cursor.execute('INSERT INTO address (address, sender) VALUES (%s, %s)', 'bob@example.com', 'abc123')

  #@...
  @untwisted.identity(listen().then)
  class server(smtp.server):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.server.mail):
        sender = staticmethod(untwisted.each(lambda: equal('alice@example.com', str((yield)))))
        recipient = staticmethod(untwisted.each(lambda: equal('abc123@example.com', str((yield)))))
        content = staticmethod(untwisted.each(lambda: equal('\r\n'.join((
          'From: notAlice@example.com',
          'Message-ID: <1234567890@example.com>',
          '',
          'Expect')), (yield))))

      ctx = yield sample.__get__(ctx)()

      # QUIT
      yield smtp.server.mail.__get__(ctx)()

  #@...
  @untwisted.identity(connect().then)
  class client(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.client.mail):
        sender = iter(('alice@example.com',)).next
        recipient = iter(('abc123@example.com',)).next
        content = iter(('\r\n'.join((
          'From: notAlice@example.com',
          'Message-ID: <1234567890@example.com>',
          '',
          'Expect')),)).next

      yield sample.__get__(ctx)()

  return client

for cursor in conn:
  equiv((('abc123',),), cursor.execute('SELECT sender FROM message_id WHERE message_id = %s', '1234567890@example.com'))
