#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(4)

@sdfg
def _():

  #@...
  @untwisted.identity(listen().then)
  class server(smtp.server):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.server.mail):
        sender = staticmethod(untwisted.each(lambda: equal('alice@example.com', str((yield)))))
        recipient = staticmethod(untwisted.each(lambda: equal('bob@example.com', str((yield)))))

        @staticmethod
        @untwisted.each
        def content():
          equal('Expect', str((yield)))

          raise smtp.reply(234, 'Expect')

      ctx = yield sample.__get__(ctx)()

      # QUIT
      yield smtp.server.mail.__get__(ctx)()

  #@...
  @untwisted.identity(connect().then)
  class client(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.client.mail):
        sender = iter(('alice@example.com',)).next
        recipient = iter(('bob@example.com',)).next
        content = iter(('Expect',)).next

      yield sample.__get__(ctx)().then(untwisted.compose(untwisted.partial(equal, '234 Expect\r\n'), str))

  return client
