#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(21)

@sdfg
def _():

  #@listen().then
  @untwisted.identity(listen().then)
  @promise.continuate
  def _(transport):
    transport.write('220\r\n')

    equal('EHLO example.com\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('MAIL FROM:<alice@example.com>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('RCPT TO:<bob@example.com>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('DATA\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('456 Expect\r\n')

    equal('RSET\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('MAIL FROM:<carol@example.com>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('RCPT TO:<dave@example.com>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('DATA\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('354\r\n')

    equal('Expect\r\n.\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('QUIT\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('221\r\n')

  #@connect().then
  @untwisted.identity(connect().then)
  @promise.continuate
  def _(transport):
    equal('220\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('EHLO example.com\r\n')

    equal('250\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('MAIL FROM:<alice@example.com>\r\n')

    equal('250 2.1.0 Success\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('RCPT TO:<bob@example.com>\r\n')

    equal('250 2.1.5 Destination address valid\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('DATA\r\n')

    equal('354 Start mail input; end with <CRLF>.<CRLF>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('Content\r\n.\r\n')

    equal('456 Expect\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('MAIL FROM:<carol@example.com>\r\n')

    equal('250 2.1.0 Success\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('RCPT TO:<dave@example.com>\r\n')

    equal('250 2.1.5 Destination address valid\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('DATA\r\n')

    equal('354 Start mail input; end with <CRLF>.<CRLF>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('Expect\r\n.\r\n')

    equal('250\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('QUIT\r\n')

    equal('221\r\n', (yield transport.protocol.dataReceived.shift()))

  yield _
