#!/usr/bin/env python

from mail.test import equal, expect, ok
from twisted.enterprise import adbapi
from twisted.internet import protocol, reactor, threads
from twisted.web import http

expect(1)

def insert():
  conn = adbapi.Connection(pool)
  trans = adbapi.Transaction(pool, conn)

  trans.execute('INSERT INTO address (address, sender) VALUES (%s, %s)', ('bob@example.com', 'abc123'))
  trans.close()

def callback(result):
  class Client(http.HTTPClient):
    def connectionMade(self):
      self.sendCommand('GET', '/bob@example.com')

      self.endHeaders()

    def handleResponse(self, response):
      equal('abc123', response)

  class ClientFactory(protocol.ClientFactory):
    protocol = Client

  factory = ClientFactory()
  reactor.connectTCP('localhost', 8743, factory)

threads.deferToThreadPool(reactor, pool.threadpool, insert).addCallback(callback)
