#!/usr/bin/env python

from cookie.test import *
from twisted.internet import protocol
from twisted.web import http

expect(1)

@sdfg
def _():
  try:
    cursor = conn.cursor()
    #cursor.execute('INSERT INTO address (address, sender) VALUES (%s, %s)', 'bob@example.com', 'abc123')
    cursor.execute('INSERT INTO address (address, sender) VALUES (%s, %s)', ('bob@example.com', 'abc123'))

  finally:
    cursor.close()

  @untwisted.partial(reactor.connectTCP, 'localhost', 8743)
  @untwisted.call
  class _(protocol.ClientFactory):
    class protocol(http.HTTPClient):
      def connectionMade(ctx):
        ctx.sendCommand('GET', '/bob@example.com')

        ctx.endHeaders()

      handleResponse = staticmethod(untwisted.partial(equal, 'abc123'))

  return promise.promise()
