#!/usr/bin/env python

from cookie.test import *
from twisted.internet import protocol
from twisted.web import http

expect(2)

@sdfg
def _():

  @untwisted.partial(reactor.connectTCP, 'localhost', 8743)
  @untwisted.call
  class _(protocol.ClientFactory):
    class protocol(http.HTTPClient):
      def connectionMade(ctx):
        ctx.sendCommand('GET', '/notAddrSpec')

        ctx.endHeaders()

      def handleResponse(ctx, response):
        pass

      handleStatus = lambda ctx, version, status, message: equal('404', status)

  return promise.promise()

for cursor in conn:
  equiv((), cursor.execute('SELECT sender FROM address'))
