#!/usr/bin/env python

from cookie.test import *
from twisted.internet import protocol
from twisted.web import http

expect(2)

@sdfg
def _():

  @untwisted.call
  class factory(protocol.ClientFactory):
    class protocol(http.HTTPClient):
      def connectionMade(ctx):
        ctx.sendCommand('GET', '/notAddrSpec')

        ctx.endHeaders()

      def handleResponse(ctx, body):
        pass

      handleStatus = lambda ctx, version, code, phrase: equal('404', code)

  reactor.connectTCP('localhost', 8743, factory)

  return promise.promise()

for cursor in conn:
  equiv((), cursor.execute('SELECT sender FROM address'))
