#!/usr/bin/env python

from mail.test import equal, expect, ok
from twisted.enterprise import adbapi
from twisted.internet import protocol, reactor, threads
from twisted.web import http

expect(1)

class Client(http.HTTPClient):
  def connectionMade(self):
    self.sendCommand('GET', '/bob@example.com')

    self.endHeaders()

  def handleResponse(self, response):
    global sender

    sender = response

class ClientFactory(protocol.ClientFactory):
  protocol = Client

factory = ClientFactory()
reactor.connectTCP('localhost', 8743, factory)

def timeout():
  def select():
    conn = adbapi.Connection(pool)
    trans = adbapi.Transaction(pool, conn)

    trans.execute('SELECT sender FROM address WHERE address = %s', 'bob@example.com')
    result = trans.fetchall()
    trans.close()

    return result

  def callback(result):
    equal(result, ((sender,),))

  threads.deferToThreadPool(reactor, pool.threadpool, select).addCallback(callback)

reactor.callLater(1, timeout)
