#!/usr/bin/env python

from cookie.test import *
from twisted.internet import protocol
from twisted.web import http

expect(1)

@sdfg
def _():

  @untwisted.partial(reactor.connectTCP, 'localhost', 8743)
  @untwisted.call
  class _(protocol.ClientFactory):
    class protocol(http.HTTPClient):
      def connectionMade(ctx):
        ctx.sendCommand('GET', '/bob@example.com')

        ctx.endHeaders()

      def handleResponse(ctx, response):
        for cursor in conn:
          equiv(((response,),), cursor.execute('SELECT sender FROM address WHERE address = %s', 'bob@example.com'))

  return promise.promise()
