#!/usr/bin/env python

from mail import test
from mail.test import equal, expect, ok
from StringIO import StringIO
from twisted.enterprise import adbapi
from twisted.internet import reactor, threads

expect(3)

def insert():
  conn = adbapi.Connection(pool)
  trans = adbapi.Transaction(pool, conn)

  trans.execute('INSERT INTO message_id (message_id, sender) VALUES (%s, %s)', ('1234567890@example.com', 'abc123'))
  trans.close()

def callback(result):
  factory = test.ServerFactory()
  factory.expect = [[{
    'data': '''Received: from example.com (localhost [127.0.0.1])
  by example.com (Postfix) with ESMTPA
  for <notbob@example.com>; Fri, 13 Feb 2009 15:31:30 -0800 (PST)
From: abc123@nottheoilrig.com
In-Reply-To: <1234567890@example.com>

la di da
''',
    'from': 'abc123@nottheoilrig.com',
    'to': ['bob@example.com'] }]]

  reactor.listenTCP(1894, factory)

  factory = test.ClientFactory()
  factory.message = [{
    'data': StringIO('''Received: from example.com (localhost [127.0.0.1])
  by example.com (Postfix) with ESMTPA
  for <notbob@example.com>; Fri, 13 Feb 2009 15:31:30 -0800 (PST)
From: notalice@example.com
In-Reply-To: <1234567890@example.com>

la di da
'''),
    'from': 'alice@example.com',
    'to': ['bob@example.com'] }]

  reactor.connectTCP('localhost', 1438, factory)

threads.deferToThreadPool(reactor, pool.threadpool, insert).addCallback(callback)
