#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(4)

@sdfg
def _():

  #@listen().then
  @untwisted.identity(listen().then)
  class _(smtp.server):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.server.mail):

        @promise.continuate
        def sender(ctx, sender):
          ctx.ctx.transport.write(str(smtp.reply(456, 'Expect')))

          equal('MAIL FROM:<carol@example.com>\r\n', str((yield ctx.ctx.command())))

        recipient = staticmethod(untwisted.each(lambda: equal('dave@example.com', str((yield)))))
        content = staticmethod(untwisted.each(lambda: equal('da di la', str((yield)))))

      ctx = yield sample.__get__(ctx)()

      # QUIT
      yield smtp.server.mail.__get__(ctx)()

  #@connect().then
  @untwisted.identity(connect().then)
  class _(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.client.mail):
        sender = iter(('alice@example.com',)).next
        recipient = iter(('bob@example.com',)).next
        content = iter(('la di da',)).next

      sample = sample.__get__(ctx)()

      @sample.then
      class _:
        throw = staticmethod(lambda type, value, traceback: equal('456 Expect\r\n', str(value)))

      ctx = yield sample

      class sample(smtp.client.mail):
        sender = iter(('carol@example.com',)).next
        recipient = iter(('dave@example.com',)).next
        content = iter(('da di la',)).next

      yield sample.__get__(ctx)()

  yield _
