#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(6)

@sdfg
def _():

  #@listen().then
  @untwisted.identity(listen().then)
  class _(smtp.server):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.server.mail):
        sender = staticmethod(untwisted.each(lambda: equal('alice@example.com', str((yield)))))
        recipient = staticmethod(untwisted.each(lambda: equal('bob@example.com', str((yield)))))
        content = staticmethod(untwisted.each(lambda: equal('Expect', (yield))))

      ctx = yield sample.__get__(ctx)()

      class sample(smtp.server.mail):
        sender = staticmethod(untwisted.each(lambda: equal('carol@example.com', str((yield)))))
        recipient = staticmethod(untwisted.each(lambda: equal('dave@example.com', str((yield)))))
        content = staticmethod(untwisted.each(lambda: equal('Tcepxe', (yield))))

      ctx = yield sample.__get__(ctx)()

      # QUIT
      yield smtp.server.mail.__get__(ctx)()

  #@connect().then
  @untwisted.identity(connect().then)
  class _(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.client.mail):
        sender = iter(('alice@example.com',)).next
        recipient = iter(('bob@example.com',)).next
        content = iter(('Expect',)).next

      ctx = yield sample.__get__(ctx)()

      class sample(smtp.client.mail):
        sender = iter(('carol@example.com',)).next
        recipient = iter(('dave@example.com',)).next
        content = iter(('Tcepxe',)).next

      yield sample.__get__(ctx)()

  yield _
