#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(6)

@sdfg
def _():
  for cursor in conn:
    cursor.executemany('INSERT INTO address (address, sender) VALUES (%s, %s)', ('bob@example.com', 'abc123'), ('carol@example.com', '321cba'))

  #@listen().then
  @untwisted.identity(listen().then)
  class server(smtp.server):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.server.mail):
        sender = staticmethod(untwisted.each(lambda: equal('abc123@nottheoilrig.com', str((yield)))))
        recipient = staticmethod(untwisted.each(lambda: equal('bob@example.com', str((yield)))))
        content = staticmethod(untwisted.each(lambda: equal('\r\n'.join(('Received: from example.com (localhost [127.0.0.1])',
          '  by example.com (Postfix) with ESMTPA;',
          '  Fri, 13 Feb 2009 15:31:30 -0800 (PST)',
          'From: abc123@nottheoilrig.com',
          '',
          'Expect')), (yield))))

      ctx = yield sample.__get__(ctx)()

      class sample(smtp.server.mail):
        sender = staticmethod(untwisted.each(lambda: equal('321cba@nottheoilrig.com', str((yield)))))
        recipient = staticmethod(untwisted.each(lambda: equal('carol@example.com', str((yield)))))
        content = staticmethod(untwisted.each(lambda: equal('\r\n'.join(('Received: from example.com (localhost [127.0.0.1])',
          '  by example.com (Postfix) with ESMTPA;',
          '  Fri, 13 Feb 2009 15:31:30 -0800 (PST)',
          'From: 321cba@nottheoilrig.com',
          '',
          'Expect')), (yield))))

      ctx = yield sample.__get__(ctx)()

      # QUIT
      yield smtp.server.mail.__get__(ctx)()

  #@connect().then
  @untwisted.identity(connect().then)
  class client(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.client.mail):
        sender = iter(('alice@example.com',)).next
        recipient = iter(('bob@example.com', 'carol@example.com')).next
        content = iter(('\r\n'.join(('Received: from example.com (localhost [127.0.0.1])',
          '  by example.com (Postfix) with ESMTPA;',
          '  Fri, 13 Feb 2009 15:31:30 -0800 (PST)',
          'From: notAlice@example.com',
          '',
          'Expect')),)).next

      yield sample.__get__(ctx)()

  return client
