#!/usr/bin/env python

from mail import test
from mail.test import equal, expect, ok
from StringIO import StringIO
from twisted.internet import reactor

expect(6)

factory = test.ServerFactory()
factory.expect = [[{
  'data': '''
da di la
''',
  'from': 'carol@example.com',
  'to': ['dave@example.com'] }], [{
  'data': '''
la di da
''',
  'from': 'alice@example.com',
  'to': ['bob@example.com'] }]]

reactor.listenTCP(1894, factory)

factory = test.ClientFactory()
factory.message = [{
  'data': StringIO('''
la di da
'''),
  'from': 'alice@example.com',
  'to': ['bob@example.com'] }]

reactor.connectTCP('localhost', 1438, factory)

factory = test.ClientFactory()
factory.message = [{
  'data': StringIO('''
da di la
'''),
  'from': 'carol@example.com',
  'to': ['dave@example.com'] }]

reactor.connectTCP('localhost', 1438, factory)
