#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(6)

@sdfg
def _():

  #@listen().then
  @untwisted.identity(listen().then)
  class _(smtp.server):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.server.mail):
        mail = staticmethod(untwisted.each(lambda: equal('alice@example.com', str((yield)))))
        recipient = staticmethod(untwisted.each(lambda: equal('bob@example.com', str((yield)))))
        data = staticmethod(untwisted.each(lambda: equal('\r\n'.join(('',
          'la di da')), (yield))))

      ctx = yield sample.__get__(ctx)()

      # QUIT
      yield smtp.server.mail.__get__(ctx)()

  #@listen().then
  @untwisted.identity(listen().then)
  class _(smtp.server):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.server.mail):
        mail = staticmethod(untwisted.each(lambda: equal('carol@example.com', str((yield)))))
        recipient = staticmethod(untwisted.each(lambda: equal('dave@example.com', str((yield)))))
        data = staticmethod(untwisted.each(lambda: equal('\r\n'.join(('',
          'da di la')), (yield))))

      ctx = yield sample.__get__(ctx)()

      # QUIT
      yield smtp.server.mail.__get__(ctx)()

  #@connect().then
  @untwisted.identity(connect().then)
  class _(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.client.mail):
        mail = iter(('alice@example.com',)).next
        recipient = iter(('bob@example.com',)).next
        data = iter(('\r\n'.join(('',
          'la di da')),)).next

      yield sample.__get__(ctx)()

  #@connect().then
  @untwisted.identity(connect().then)
  class _(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.client.mail):
        mail = iter(('carol@example.com',)).next
        recipient = iter(('dave@example.com',)).next
        data = iter(('\r\n'.join(('',
          'da di la')),)).next

      yield sample.__get__(ctx)()

  return _
