#!/usr/bin/env python

from mail import test
from mail.test import equal, expect, ok
from StringIO import StringIO
from twisted.internet import reactor

expect(6)

factory = test.ServerFactory()

protocol = test.Server()
protocol.expect = [{
  'data': '''
la di da
''',
  'from': 'alice@example.com',
  'to': ['bob@example.com'] }, {
  'data': '''
la di da
''',
  'from': 'alice@example.com',
  'to': ['carol@example.com'] }]

factory.protocol.append(protocol)

reactor.listenTCP(1894, factory)

factory = test.ClientFactory()

protocol = test.Client()
protocol.message = [{
  'data': StringIO('''
la di da
'''),
  'from': 'alice@example.com',
  'to': ['bob@example.com', 'carol@example.com'] }]

factory.protocol.append(protocol)

reactor.connectTCP('localhost', 1438, factory)
