#!/usr/bin/env python

from mail.test import equal, expect, ok
from StringIO import StringIO
from twisted.internet import defer, protocol, reactor
from twisted.mail import smtp

expect(6)

class Message:
  def __init__(self):
    self.data = []

  def eomReceived(self):
    equal("\n".join(self.data) + "\n", '''
la di da
''')

    return defer.succeed(None)

  def lineReceived(self, line):
    self.data.append(line)

expected = ['bob@example.com', 'carol@example.com']

class Server(smtp.ESMTP):
  def do_UNKNOWN(self, rest):
    raise

  def receivedHeader(self, helo, origin, recipients):
    pass

  def validateFrom(self, helo, origin):
    equal(str(origin), 'alice@example.com')

    return origin

  def validateTo(self, user):
    global expected

    equal(str(user), expected[0])

    expected = expected[1:]

    return Message

# ESMTPFactory doesn't exist
class ServerFactory(smtp.SMTPFactory):
  protocol = Server

factory = ServerFactory()
reactor.listenTCP(1894, factory)

message = [{
  'data': StringIO('''
la di da
'''),
  'from': 'alice@example.com',
  'to': ['bob@example.com', 'carol@example.com'] }]

class Client(smtp.ESMTPClient):

  # Shortcut ESMTPClient.__init__(), no authentication or TLS
  def __init__(self, *args, **kw):
    self.secret = None

    return smtp.SMTPClient.__init__(self, *args, **kw)

  def getMailData(self):
    return message[0]['data']

  def getMailFrom(self):
    return message[0]['from']

  def getMailTo(self):
    return message[0]['to']

  def smtpState_msgSent(self, code, resp):
    global message

    message = message[1:]
    if message:
      self._from = None
      self.toAddressesResult = []

      return smtp.ESMTPClient.smtpState_msgSent(self, code, resp)

    # No more messages to send
    self._disconnectFromServer()

class ClientFactory(protocol.ClientFactory):
  protocol = Client

  def buildProtocol(self, addr):
    return self.protocol('example.com')

factory = ClientFactory()
reactor.connectTCP('localhost', 1438, factory)
