#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(3)

@sdfg
def _():
  for cursor in conn:
    cursor.execute('INSERT INTO message_id (message_id, sender) VALUES (%s, %s)', '1234567890@example.com', 'abc123')

  #@listen().then
  @untwisted.identity(listen().then)
  class _(smtp.server):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.server.mail):
        sender = staticmethod(untwisted.each(lambda: equal('abc123@nottheoilrig.com', str((yield)))))
        recipient = staticmethod(untwisted.each(lambda: equal('bob@example.com', str((yield)))))
        content = staticmethod(untwisted.each(lambda: equal('\r\n'.join(('Received: from example.com (localhost [127.0.0.1])',
          '  by example.com (Postfix) with ESMTPA',
          '  for <notBob@example.com>; Fri, 13 Feb 2009 15:31:30 -0800 (PST)',
          'From: abc123@nottheoilrig.com',
          'References: <1234567890@example.com>',
          '',
          'la di da')), (yield))))

      ctx = yield sample.__get__(ctx)()

      # QUIT
      yield smtp.server.mail.__get__(ctx)()

  #@connect().then
  @untwisted.identity(connect().then)
  class _(smtp.client):

    @untwisted.each
    def mail():
      ctx = yield

      class sample(smtp.client.mail):
        sender = iter(('alice@example.com',)).next
        recipient = iter(('bob@example.com',)).next
        content = iter(('\r\n'.join(('Received: from example.com (localhost [127.0.0.1])',
          '  by example.com (Postfix) with ESMTPA',
          '  for <notBob@example.com>; Fri, 13 Feb 2009 15:31:30 -0800 (PST)',
          'From: notAlice@example.com',
          'References: <1234567890@example.com>',
          '',
          'la di da')),)).next

      yield sample.__get__(ctx)()

  yield _
