#!/usr/bin/env python

from cookie.test import *
from untwisted import smtp

expect(14)

@sdfg
def _():

  #@listen().then
  @untwisted.identity(listen().then)
  @promise.continuate
  def _(transport):
    transport.write('220\r\n')

    equal('EHLO example.com\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250-example.com Success\r\n250 PIPELINING\r\n')

    equal('MAIL FROM:<alice@example.com>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('RCPT TO:<bob@example.com>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('DATA\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('354\r\n')

    equal('la di da\r\n.\r\n', (yield transport.protocol.dataReceived.shift()))

    yield timeout(1)

    transport.write('234 Expect\r\n')

    equal('MAIL FROM:<carol@example.com>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('RCPT TO:<dave@example.com>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n')

    equal('DATA\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('354\r\n')

    equal('da di la\r\n.\r\nQUIT\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('250\r\n221\r\n')

  #@connect().then
  @untwisted.identity(connect().then)
  @promise.continuate
  def _(transport):
    equal('220\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('EHLO example.com\r\n')

    equal('250-example.com Success\r\n250 PIPELINING\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('MAIL FROM:<alice@example.com>\r\nRCPT TO:<bob@example.com>\r\nDATA\r\n')

    equal('250 2.1.0 Success\r\n250 2.1.5 Destination address valid\r\n354 Start mail input; end with <CRLF>.<CRLF>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('la di da\r\n.\r\nMAIL FROM:<carol@example.com>\r\nRCPT TO:<dave@example.com>\r\nDATA\r\n')

    equal('234 Expect\r\n250 2.1.0 Success\r\n250 2.1.5 Destination address valid\r\n354 Start mail input; end with <CRLF>.<CRLF>\r\n', (yield transport.protocol.dataReceived.shift()))

    transport.write('da di la\r\n.\r\nQUIT\r\n')

    equal('250\r\n221\r\n', (yield transport.protocol.dataReceived.shift()))

  yield _
