#!/usr/bin/env python

import sys
from mail.test import config
from twisted.enterprise import adbapi
from twisted.internet import reactor, threads
from twisted.python import log

log.startLogging(sys.stdout)

def timeout():
  try:
    if config['expect'] != config['count']:
      print 'FAIL %s %s' % (config['expect'], config['count'])

  except KeyError:
    pass

  reactor.stop()

reactor.callLater(2, timeout)

pool = adbapi.ConnectionPool('MySQLdb', db='cookie', user='root')

def delete():
  conn = adbapi.Connection(pool)
  trans = adbapi.Transaction(pool, conn)

  trans.execute('DELETE FROM address')
  trans.close()

def callback(result):
  def delete():
    conn = adbapi.Connection(pool)
    trans = adbapi.Transaction(pool, conn)

    trans.execute('DELETE FROM message_id')
    trans.close()

  def callback(result):
    execfile(sys.argv[1], globals())

  threads.deferToThreadPool(reactor, pool.threadpool, delete).addCallback(callback)

threads.deferToThreadPool(reactor, pool.threadpool, delete).addCallback(callback)

reactor.run()
